name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Update Release Draft
      uses: release-drafter/release-drafter@v5.21.1
      with:
        config-name: release-drafter.yml
        disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

