name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  call_reusable_workflow: 
    uses: jonathan-kline/hello-world/.github/workflows/Release-Drafter.yml@main
    with:
      config-path: .github/release-drafter.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

