
name: Team Label
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]
jobs:
  call_reusable_workflow:
    name: Team Labeler
    uses: jonathan-kline/hello-world/.github/workflows/Team-Label.yml@main
    with:
      configuration-path: .github/teams.yml
      teams-repo: jonathan-kline/hello-world
      teams-branch: main
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
